- name: 龙井
  image: /assets/images/longjing.png
  description: >
    西湖龙井是中国十大名茶之一，属绿茶，其产于浙江省杭州市西湖龙井村周围群山，并因此得名，具有1200多年历史。
    清乾隆游览杭州西湖时，盛赞西湖龙井茶，把狮峰山下胡公庙前的十八棵茶树封为“御茶”。西湖龙井按外形和内质的优次分作1～8级。
    特级西湖龙井茶扁平光滑挺直，色泽嫩绿光润，香气鲜嫩清高，滋味鲜爽甘醇，叶底细嫩呈朵。清明节前采制的龙井茶简称明前龙井，美称女儿红，“院外风荷西子笑，明前龙井女儿红。”
    西湖龙井茶与西湖一样，是人、自然、文化三者的完美结晶，是西湖地域文化的重要载体。
- name: 普洱
  image: /assets/images/puer.png
  description: >
    普洱茶是产自中国云南省，以云南大叶种晒青毛茶为原料，经过特定工艺加工而成的一种后发酵茶。普洱茶以其越陈越香的特点而闻名，被誉为“可以喝的古董”。
    普洱茶讲究冲泡技巧和品饮艺术，可清饮，可混饮。普洱茶茶汤橙黄浓厚，香气高锐持久，香型独特，滋味浓醇，经久耐泡。
    普洱茶茶性温和，暖胃不伤胃，这点对熟普洱茶尤为明显，普洱茶的后发酵过程是由大量微生物参与的，在微生物的作用下，茶叶中的大分子多糖类物质转化成了大量新的可溶性单糖和寡糖，维生素C成倍增加，这些物质对提高人体免疫系统功能发挥重要的作用。
- name: 太平猴魁
  image: /assets/images/houkui.png
  description: >
    太平猴魁，中国传统名茶，中国历史名茶之一，属于绿茶类尖茶，产于安徽省黄山市北麓的黄山区（原太平县）新明、龙门、三口一带，为尖茶之极品，久享盛名。
    外形叶裹顶芽，有“两刀夹一枪”及“二叶抱一芽”之喻，芽藏锋露尖，顶尖尾削，形成两端尖细，有“猴魁两头尖，不散不翘不卷边”之称。
    条形挺直壮实，色绿光润，普生茸毫，头泡香高，二泡味浓，冲泡三四次，滋味不减，兰香犹存。
- name: 碧螺春
  image: /assets/images/biluochun.jpg
  description: >
    洞庭山碧螺春茶是与西湖龙井茶齐名的中国十大名茶之一，产于苏州太湖流域的东洞庭山（现苏州吴中区东山镇）和西洞庭山（现苏州太湖西山岛上的吴中区金庭镇）两地。
    洞庭山的茶林和果园融为一体，茶树和桃、李、杏、梅、枇杷等果树交错种植，是典型的茶果间作套种模式。
    洞庭山碧螺春茶的制作工艺要求很高，高品质的茶叶需要全手工炒制。
- name: 寿眉
  image: /assets/images/shoumei.png
  description: >
    寿眉，乃以福鼎大白、福鼎白茶树制成的白茶。寿眉叶张稍肥嫩，芽叶连枝，无老梗，叶整卷如眉，香气清纯。
    其中用茶芽叶制成的毛茶称为“小白”，以区别于福鼎大白茶、政和大白茶茶树芽叶制成的“大白”毛茶。
- name: 白毫银针
  image: /assets/images/baihaoyinzhen.png
  description: >
    白毫银针，创制于1796年，是中国六大茶类之一的白茶，原产地在福建，主要产区为福鼎、柘荣、政和、松溪、建阳等地，素有中国十大名茶的称号，素有茶中“美女”、“茶王”之美称。
    其外观特征挺直似针，满披白毫，如银似雪，成品茶长约3cm。
- name: 蒙顶黄芽
  image: /assets/images/mengding.png
  description: >
    蒙顶黄芽，是芽形黄茶之一，产于四川省雅安市蒙顶山。蒙顶茶栽培始于西汉，距今已有二千年的历史，古时为贡品供历代皇帝享用。
    蒙顶黄芽外形扁直，芽条匀整，色泽嫩黄，芽毫显露，花香幽长，汤色黄亮透碧，滋味鲜醇回甘，叶底全芽嫩黄采摘于春分时节，茶树上有10%的芽头鳞片展开，即可开园采摘。
    选圆肥单芽和一芽一叶初展的芽头，经复杂制作工艺，使成茶芽条匀整，扁平挺直，色泽黄润，金毫显露；汤色黄中透碧，甜香鲜嫩，甘醇鲜爽。为黄茶之极品。
- name: 温州黄汤
  image: /assets/images/huangtang.png
  description: >
    温州黄汤亦称温州黄汤、平阳黄汤。产于平阳、苍南、泰顺、瑞安、永嘉等地，以泰顺的东溪与平阳的北港所产品质最佳。
    条索细紧纤秀，色泽黄绿多毫；汤色橙黄鲜明，叶底嫩匀成朵，香气清高幽远，滋味和酸鲜爽。成茶以“三黄”，即“色黄，汤黄，叶底黄”闻名。
- name: 大叶青
  image: /assets/images/dayeqing.png
  description: >
    大叶青茶为广东的特产。大叶青茶也称广东大叶青，主要产于广东省韶关、肇庆、湛江等县市、属于黄茶，是黄大茶的代表品种之一。
    制法是先萎凋后杀青，再揉捻闷堆。这与其它黄茶不同。产品品质具有黄茶的一般特点，所以也归属共同茶类。
    其产地为广东省韶关、肇庆、湛江等县市。广东大叶青为属黄茶类，但与其他黄茶制法不同，其先萎凋后杀青，再揉捻闷堆。
    杀青前的萎凋和揉捻后闷黄的主要目的是消除青气涩味，促进香味醇和纯正。
- name: 安化黑茶
  image: /assets/images/anhua.png
  description: >
    安化黑茶是六大基本茶类之一，属于后发酵茶，主要产品以茯砖、黑砖、花砖、青砖、湘尖等产品为主。
    在古代，一部分内销山西、陕西、甘肃、绥远、宁夏、新疆、西藏、蒙古等地，一部分加工制压成砖，除内销西北各地外，还外销苏俄，特称“砖茶”。
    安化黑茶是中国黑茶的始祖，在唐代（856年）的史料中记载为“渠江薄片”，曾列为朝廷贡品，明嘉靖三年（1524年）就正式创制出了安化黑茶。
    至16世纪末期，安化黑茶已位居中国领先地位，万历年间被定为官茶，大量远销西北。
- name: 茉莉花茶
  image: /assets/images/molihua.png
  description: >
    茉莉花茶是将茶叶和茉莉鲜花进行拼和、窨制，使茶叶吸收花香而成的茶叶。又叫茉莉香片，属于花茶，茶坯为绿茶，成品将茉莉花去除，亦属于绿茶的一种，已有1000多年历史。
    茉莉花原产于印度，西汉时从陆路和海上丝绸之路引入中国，落户福州，产生了用茉莉花窨制绿茶的技术。
    ]世界茉莉花茶发源地为福建福州，其茶香与茉莉花香交互融合，有“窨得茉莉无上味，列作人间第一香”的美誉。
    茉莉花茶是花茶的大宗产品，产区辽阔，产量高，品种丰富。在清朝时被列为贡品，有150多年历史。
- name: 八角亭龙须茶
  image: /assets/images/longxu.png
  description: >
    八角亭龙须茶又称“束茶”，属乌龙茶类，产于福建省武夷山市及建瓯，早在清康熙五十六年（1717）就有文献对其记载。
    其外形壮直，形似“龙须”，色泽墨绿，滋味醇厚，汤色橙黄，耐冲泡，具有防癌症、降血脂、抗衰老等特殊功效。
    八角亭龙须茶的制作经过萎凋、鲜叶杀青、揉捻、理条、扎束制作而成。
- name: 岳西翠兰
  image: /assets/images/cuilan.png
  description: >
    岳西翠兰，安徽省岳西县特产，国家地理标志产品。
    岳西翠兰其外形优美，芽叶相连，自然舒展，酷似小兰花；其汤翠绿明亮，香气持久；其味醇厚而回甘。
    该茶外形芽叶相连，舒展成朵，色泽翠绿，形似兰花，香气清高持久，汤色浅绿明亮，滋味醇浓鲜爽，叶底嫩绿明亮。
- name: 汉中仙毫
  image: /assets/images/xianhao.png
  description: >
    汉中仙毫，陕西省汉中市特产，中国国家地理标志产品汉中茶园多位于竹木繁茂、雨量丰沛的大巴山北麓海拔800―1600米的缓坡地上。
    这里冬无严寒、夏无酷暑，气候温和，森林覆盖率达60%左右，被公认是地球上同纬度地带中适合人类生活和适合茶树生长的地方，
    是国家实施南水北调中线工程的重要水源保护地，也是联合国教科文组织授予的“世界人与自然生物圈保护区”，生态环境优越。
    汉中仙毫品质优异。纬度高、海拔高、云雾几率高、富含锌硒、远离污染的自然地理优势和生长环境使汉中茶具有香高、味浓、耐泡、形美、保健五大特点。
- name: 涌溪火青
  image: /assets/images/huoqing.png
  description: >
    涌溪火青，安徽省泾县特产，全国农产品地理标志。涌溪火青属珠茶，生产历史已有五百余载，曾为历朝之贡茶。
    产于安徽省泾县城东70千米涌溪山的枫坑、盘坑、石井坑湾头山一带。涌溪火青外形独特美观，颗粒细嫩重实，色泽墨绿莹润，银毫密披。
    冲泡形似兰花舒展，汤色杏黄明亮，清香馥郁，味浓甘爽，并有特殊清香。可冲泡4—5次，以第2—3次最好。其具有明目清心，止渴解暑、利尿解毒、提神消腻之功效。
- name: 天山绿茶
  image: /assets/images/tianshan.jpg
  description: >
    天山绿茶历史悠久，多制作高档花茶茶坯，属于青绿茶类。产于福建省闽东地带的天山山脉，地跨宁德、古田、屏南三县。
    其品质特点：条索细长袄匀整，白毫显身，具有三绿（外形翠绿、汤色碧绿、叶底嫩绿），香气浓久清高，回味生甜，浓而臾口，耐于冲泡。
    代表性花色品种：天山毛峰、天山银毫、清水绿茶。天山绿茶的制作工艺可分为传统工艺（鲜叶摊凉、杀青、揉捻、烘焙）和机械加工（凉青、杀青、揉捻、烘干（毛火和足火））。
    天山绿茶中的茶多酚具有杀伤癌细胞和抑制癌细胞生长的功效。
- name: 金骏眉
  image: /assets/images/jinjunmei.png
  description: >
    金骏眉诞生于2005年，是一种顶级正山小种红茶。是以武夷山市星村镇桐木村为中心的武夷山国家级自然保护区565平方公里内的高山茶树单芽为原料，
    采用萎凋、揉捻、发酵、过红锅、干燥的独特工艺制作而成，具有“汤色金黄，汤中带甘，甘里透香”等品质特征。
    “骏眉”系列红茶就是企业制茶技术改革创新的典型代表，金骏眉、银骏眉均是高端顶级红茶的代表。金骏眉对原材料要求高，全程手工制作，价格也十分名贵。
- name: 水仙
  image: /assets/images/shuixian.png
  description: >
    水仙茶是福建茶农创制的名茶，属于中国茶叶优良品种之一，是福建乌龙茶类中的一种。原产于闽北。
    一千年前，建阳、建瓯一带就有这种茶树，但人工栽培却是距今三百多年前的清康熙年间（1662-1722）。
    水仙茶列“中国国家级茶树良种”48个之首，又是全国41个半乔木大叶型茶树良种的第一个，发源于福建省建阳市唯一的茶树良种。
    汤色橙黄、香如兰花、滋味醇厚回甘。
