- name: 龙井
  image: /assets/images/longjing.png
  description: >
    西湖龙井是中国十大名茶之一，属绿茶，其产于浙江省杭州市西湖龙井村周围群山，并因此得名，具有1200多年历史。
    清乾隆游览杭州西湖时，盛赞西湖龙井茶，把狮峰山下胡公庙前的十八棵茶树封为“御茶”。西湖龙井按外形和内质的优次分作1～8级。
    特级西湖龙井茶扁平光滑挺直，色泽嫩绿光润，香气鲜嫩清高，滋味鲜爽甘醇，叶底细嫩呈朵。清明节前采制的龙井茶简称明前龙井，美称女儿红，“院外风荷西子笑，明前龙井女儿红。”
    西湖龙井茶与西湖一样，是人、自然、文化三者的完美结晶，是西湖地域文化的重要载体。
- name: 普洱
  image: /assets/images/puer.png
  description: >
    普洱茶是产自中国云南省，以云南大叶种晒青毛茶为原料，经过特定工艺加工而成的一种后发酵茶。普洱茶以其越陈越香的特点而闻名，被誉为“可以喝的古董”。
    普洱茶讲究冲泡技巧和品饮艺术，可清饮，可混饮。普洱茶茶汤橙黄浓厚，香气高锐持久，香型独特，滋味浓醇，经久耐泡。
    普洱茶茶性温和，暖胃不伤胃，这点对熟普洱茶尤为明显，普洱茶的后发酵过程是由大量微生物参与的，在微生物的作用下，茶叶中的大分子多糖类物质转化成了大量新的可溶性单糖和寡糖，维生素C成倍增加，这些物质对提高人体免疫系统功能发挥重要的作用。
- name: 太平猴魁
  image: /assets/images/houkui.png
  description: >
    太平猴魁，中国传统名茶，中国历史名茶之一，属于绿茶类尖茶，产于安徽省黄山市北麓的黄山区（原太平县）新明、龙门、三口一带，为尖茶之极品，久享盛名。
    外形叶裹顶芽，有“两刀夹一枪”及“二叶抱一芽”之喻，芽藏锋露尖，顶尖尾削，形成两端尖细，有“猴魁两头尖，不散不翘不卷边”之称。
    条形挺直壮实，色绿光润，普生茸毫，头泡香高，二泡味浓，冲泡三四次，滋味不减，兰香犹存。
- name: 碧螺春
  image: /assets/images/biluochun.jpg
  description: >
    洞庭山碧螺春茶是与西湖龙井茶齐名的中国十大名茶之一，产于苏州太湖流域的东洞庭山（现苏州吴中区东山镇）和西洞庭山（现苏州太湖西山岛上的吴中区金庭镇）两地。
    洞庭山的茶林和果园融为一体，茶树和桃、李、杏、梅、枇杷等果树交错种植，是典型的茶果间作套种模式。
    洞庭山碧螺春茶的制作工艺要求很高，高品质的茶叶需要全手工炒制。
- name: 寿眉
  image: /assets/images/shoumei.png
  description: >
    寿眉，乃以福鼎大白、福鼎白茶树制成的白茶。寿眉叶张稍肥嫩，芽叶连枝，无老梗，叶整卷如眉，香气清纯。
    其中用茶芽叶制成的毛茶称为“小白”，以区别于福鼎大白茶、政和大白茶茶树芽叶制成的“大白”毛茶。
- name: 白毫银针
  image: /assets/images/baihaoyinzhen.png
  description: >
    白毫银针，创制于1796年，是中国六大茶类之一的白茶，原产地在福建，主要产区为福鼎、柘荣、政和、松溪、建阳等地，素有中国十大名茶的称号，素有茶中“美女”、“茶王”之美称。
    其外观特征挺直似针，满披白毫，如银似雪，成品茶长约3cm。
- name: 蒙顶黄芽
  image: /assets/images/mengding.png
  description: >
    蒙顶黄芽，是芽形黄茶之一，产于四川省雅安市蒙顶山。蒙顶茶栽培始于西汉，距今已有二千年的历史，古时为贡品供历代皇帝享用。
    蒙顶黄芽外形扁直，芽条匀整，色泽嫩黄，芽毫显露，花香幽长，汤色黄亮透碧，滋味鲜醇回甘，叶底全芽嫩黄采摘于春分时节，茶树上有10%的芽头鳞片展开，即可开园采摘。
    选圆肥单芽和一芽一叶初展的芽头，经复杂制作工艺，使成茶芽条匀整，扁平挺直，色泽黄润，金毫显露；汤色黄中透碧，甜香鲜嫩，甘醇鲜爽。为黄茶之极品。
- name: 温州黄汤
  image: /assets/images/huangtang.png
  description: >
    温州黄汤亦称温州黄汤、平阳黄汤。产于平阳、苍南、泰顺、瑞安、永嘉等地，以泰顺的东溪与平阳的北港所产品质最佳。
    条索细紧纤秀，色泽黄绿多毫；汤色橙黄鲜明，叶底嫩匀成朵，香气清高幽远，滋味和酸鲜爽。成茶以“三黄”，即“色黄，汤黄，叶底黄”闻名。